apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  namespace: cogni-candidate-a
  labels:
    cogni.io/node-id: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
    cogni.io/environment: candidate-a
    cogni.io/node: node-template
spec:
  nodeId: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  environment: candidate-a
  bundle:
    ref: ghcr.io/cogni-dao/node-template@sha256:5f2bdb5c1839ec8b80b9d49a6d65e4ad2c0fc46077978a3b22bfcae66dcc4503
    source:
      repository: cogni-dao/node-template
      sha: 9de3856ae35bde7ba7d0d9dd763a3b713ecabc0c
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/node-template@sha256:1201458cd6ef913a1da53b80d82d3ab6b63bde0f228654b86f186d94f98c14e9
  workload:
    name: node-template
    publicHost: node-template-test.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
  migration:
    policy: RequireBeforeTransaction
  bootPolicy:
    onDeadline: Close
  leaseEpoch: 0
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni-candidate-a.vm.cognidao.org
