apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  namespace: cogni-candidate-a
  labels:
    cogni.io/node-id: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
    cogni.io/environment: candidate-a
    cogni.io/node: node-template
spec:
  nodeId: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  environment: candidate-a
  bundle:
    ref: ghcr.io/cogni-dao/node-template@sha256:1e345771f3aac2f9e1ec5e549bdd23eccb8495778569d8d25447e1baaf7149f7
    source:
      repository: cogni-dao/node-template
      sha: 58bb6df2881c78e0c90d88ec4c7701dd01a2ae80
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/node-template@sha256:e0a7af9828dd7df496b048da56589b0594d07bfc062cb1f11f4be3fa739cee89
  workload:
    name: node-template
    publicHost: node-template-test.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
  migration:
    policy: RequireBeforeTransaction
  bootPolicy:
    onDeadline: Close
  leaseEpoch: 0
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni-candidate-a.vm.cognidao.org
