apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-production
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: production
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:ecf3ba2fa170ee6cd9247e9a15753a17154f10fd4d58c1765f666bcdfde9f6d6
    source:
      repository: cogni-dao/toks4
      sha: 802ec1e9b44bd02e85aed16914d7798d95044363
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:a6f8beb8f563d2e7bbf9bbc12fdaff99c3c17f8969f7097ef8e8fb6205322ab5
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:a63571af6604e866aed682a44943c18adecd8d4eeb81a57dd4da13fec1d88848
  workload:
    name: toks4
    publicHost: toks4.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
          - key: LITELLM_VIRTUAL_KEY
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
