apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-production
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: production
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:4836f3c6b92adf61a50cec6a352437283eb4909b6961f9c6c2c81757872e8727
    source:
      repository: cogni-dao/toks4
      sha: 6f5c4db8dad293e193666c1897f8d292ba3595f9
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:72103a4df56bbf57e95db42376914468fb0267bbf4457fc0ae99ac2b4c4128bc
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:3792ab9939853072f236fb44ff22ec48860159c8a5ec209c71bb9b4996b8f04c
  workload:
    name: toks4
    publicHost: toks4.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
          - key: LITELLM_VIRTUAL_KEY
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
