apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-production
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: production
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:2464429a912aa86d77798445e963717c6230a28e4d6a84640fce7c4be4c35458
    source:
      repository: cogni-dao/toks4
      sha: 783b41d5b9b740d35c9d5376384c9809db1bb879
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:036daedd3931be1d60890d5880a96a9dc8934f436b191a0e297d64d6aa98b672
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:6d293c589b1d2f8d8893bec777ccd7588e572da191608bb20518210bba3fd85c
  workload:
    name: toks4
    publicHost: toks4.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: DOLTGRES_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Hold
    onGiveUp: Hold
  leaseGeneration: 2
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
