// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/appset`
 * Purpose: Pure port of `scripts/ci/render-node-appset.sh` — emit a new node's per-`(env, slug)` Argo
 *   ApplicationSet objects and the `infra/k8s/argocd/appsets/kustomization.yaml` that lists them, so the
 *   operator can author a node-formation PR without bash. One AppSet object per `(env, node)` is the
 *   structural LANE_ISOLATION fix (`bug.0378`): a flight only ever applies its own node's file. The
 *   appsets/ dir is reconciled with prune by the `cogni-appsets` app-of-apps, so a catalog-removed node's
 *   AppSet auto-prunes once its file leaves git.
 * Scope: `renderNodeAppset` substitutes the shared template (the SAME file the shell renderer feeds, so
 *   output is byte-exact and the `--check` drift gate stays green); `insertAppsetKustomization` rebuilds
 *   the WHOLE `appsets/kustomization.yaml` with the new slug folded in (env-major, node-sorted, mirroring
 *   the shell's `render_kustomization`). The old bootstrap sentinel-splice is GONE — appsets/kustomization.yaml
 *   is a self-contained kustomization generated wholesale.
 * Invariants: BYTE_EXACT_WITH_RENDERER — token substitution + whole-file ordering match `render-node-appset.sh`.
 *   IDEMPOTENT — a kustomization already listing the slug is returned unchanged.
 * Side-effects: none — pure string transforms, no IO, no env.
 * Links: scripts/ci/render-node-appset.sh, scripts/ci/node-applicationset.yaml.tmpl, bug.0378, task.5092
 * @public
 */

/**
 * The literal header of the GENERATED `infra/k8s/argocd/appsets/kustomization.yaml`, byte-exact to the
 * shell renderer's `render_kustomization` heredoc (everything up to and including the `resources:` line).
 */
const APPSETS_KUSTOMIZATION_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# The per-(env, node) ApplicationSets, reconciled with prune by the cogni-appsets
# app-of-apps (../cogni-appsets-application.yaml). One AppSet per (env, node) for
# structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

/**
 * Substitute the per-`(env, slug)` ApplicationSet template, byte-exact to the shell renderer's
 * `sed -e s/__ENV__/…/g -e s/__NODE__/…/g`. Argo `{{.name}}` goTemplate markers are left intact.
 */
export function renderNodeAppset(
  template: string,
  slug: string,
  env: string
): string {
  return template.replaceAll("__ENV__", env).replaceAll("__NODE__", slug);
}

/**
 * Canonical env render order — byte-exact to `render-node-appset.sh`'s
 * `ENVS=(candidate-a preview production)`. The file must always re-render in
 * this order regardless of the new node's birth envs (task.5017): a node born
 * into a subset must NOT drop the preview/production members of OTHER nodes.
 */
const RENDER_ENVS = ["candidate-a", "preview", "production"] as const;

/**
 * Parse the resources list of `appsets/kustomization.yaml` into per-env node-sets (task.5017).
 * Preserving which nodes are in which env block is load-bearing now that the node-set is per-env:
 * the old union-then-cartesian flattening re-inflated every env to every node.
 */
function existingNodesByEnv(
  resourceLines: readonly string[]
): Map<string, Set<string>> {
  const byEnv = new Map<string, Set<string>>(
    RENDER_ENVS.map((env) => [env, new Set<string>()])
  );
  for (const line of resourceLines) {
    const envNode = line.match(/^ {2}- (.+)-applicationset\.yaml$/)?.[1];
    if (envNode === undefined) continue;
    for (const env of RENDER_ENVS) {
      if (envNode.startsWith(`${env}-`)) {
        byEnv.get(env)?.add(envNode.slice(env.length + 1));
        break;
      }
    }
  }
  return byEnv;
}

/**
 * Render the WHOLE `appsets/kustomization.yaml` (header + apiVersion + kind + namespace + resources)
 * from the per-env node-sets, env-major + node-sorted (LC_ALL=C order ≡ ASCII codepoint sort for kebab
 * slugs), byte-exact to `render-node-appset.sh`'s `render_kustomization`.
 */
function renderKustomization(byEnv: Map<string, Set<string>>): string {
  const lines = [APPSETS_KUSTOMIZATION_HEADER];
  for (const env of RENDER_ENVS) {
    for (const node of [...(byEnv.get(env) ?? [])].sort()) {
      lines.push(`  - ${env}-${node}-applicationset.yaml`);
    }
  }
  // Trailing newline matches the shell renderer's final printf line.
  return `${lines.join("\n")}\n`;
}

/**
 * Fold `<slug>` into `infra/k8s/argocd/appsets/kustomization.yaml`, adding it ONLY to the envs in its
 * per-env node-set (`envs`), then re-rendering the WHOLE file env-major + node-sorted, byte-exact to
 * `render-node-appset.sh`'s `render_kustomization`. The sentinel-splice approach is gone: appsets/
 * kustomization.yaml is generated wholesale. Idempotent.
 */
export function insertAppsetKustomization(
  currentKustomization: string,
  slug: string,
  envs: readonly string[]
): string {
  const lines = currentKustomization.split("\n");
  const resourcesIdx = lines.indexOf("resources:");
  if (resourcesIdx === -1) {
    throw new Error(
      "infra/k8s/argocd/appsets/kustomization.yaml is missing a 'resources:' list; cannot fold in the slug."
    );
  }

  const byEnv = existingNodesByEnv(lines.slice(resourcesIdx + 1));
  if (envs.every((env) => byEnv.get(env)?.has(slug))) {
    return currentKustomization;
  }
  for (const env of envs) {
    byEnv.get(env)?.add(slug);
  }

  return renderKustomization(byEnv);
}
