// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/appset`
 * Purpose: Pure port of `scripts/ci/render-node-appset.sh` — emit a new node's per-`(env, slug)` Argo
 *   ApplicationSet objects and the PER-ENV `infra/k8s/argocd/appsets/<env>/kustomization.yaml` that lists
 *   that env's AppSets, so the operator can author a node-formation PR without bash. One AppSet object per
 *   `(env, node)` is the structural LANE_ISOLATION fix (`bug.0378`): a flight only ever applies its own
 *   node's file. Each appsets/<env>/ dir is reconciled with prune by its OWN per-env `cogni-<env>-appsets`
 *   app-of-apps, so a catalog-removed node's AppSet auto-prunes once its file leaves git — and no foreign
 *   env's AppSets ever fan onto a cluster (story.5020).
 * Scope: `renderNodeAppset` substitutes the shared template (the SAME file the shell renderer feeds, so
 *   output is byte-exact and the `--check` drift gate stays green); `insertAppsetKustomization` rebuilds
 *   the WHOLE `appsets/<env>/kustomization.yaml` for ONE env with the new slug folded in (node-sorted,
 *   mirroring the shell's per-env `render_kustomization`). The old all-envs single kustomization is GONE —
 *   each env has its own self-contained kustomization generated wholesale.
 * Invariants: BYTE_EXACT_WITH_RENDERER — token substitution + per-env whole-file ordering match
 *   `render-node-appset.sh`. IDEMPOTENT — a kustomization already listing the slug is returned unchanged.
 * Side-effects: none — pure string transforms, no IO, no env.
 * Links: scripts/ci/render-node-appset.sh, scripts/ci/node-applicationset.yaml.tmpl, bug.0378, task.5092, story.5020
 * @public
 */

/**
 * The literal header of the GENERATED `infra/k8s/argocd/appsets/<env>/kustomization.yaml`, byte-exact to the
 * shell renderer's per-env `render_kustomization` heredoc (everything up to and including the `resources:` line).
 */
const APPSETS_KUSTOMIZATION_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../<env>-appsets-application.yaml). One AppSet
# per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

/**
 * Substitute the per-`(env, slug)` ApplicationSet template, byte-exact to the shell renderer's
 * `sed -e s/__ENV__/…/g -e s/__NODE__/…/g`. Argo `{{.name}}` goTemplate markers are left intact.
 */
export function renderNodeAppset(
  template: string,
  slug: string,
  env: string
): string {
  return template.replaceAll("__ENV__", env).replaceAll("__NODE__", slug);
}

/**
 * Parse the resources list of ONE env's `appsets/<env>/kustomization.yaml` into its node-set. Each
 * resource line is `<env>-<node>-applicationset.yaml`; the full `<env>-` prefix is kept on disk (only the
 * file is nested under `<env>/`), so it is stripped here to recover the node slug.
 */
function existingNodes(
  resourceLines: readonly string[],
  env: string
): Set<string> {
  const nodes = new Set<string>();
  for (const line of resourceLines) {
    const file = line.match(/^ {2}- (.+)-applicationset\.yaml$/)?.[1];
    if (file === undefined) continue;
    if (file.startsWith(`${env}-`)) {
      nodes.add(file.slice(env.length + 1));
    }
  }
  return nodes;
}

/**
 * Render the WHOLE `appsets/<env>/kustomization.yaml` (header + apiVersion + kind + namespace + resources)
 * for ONE env from its node-set, node-sorted (LC_ALL=C order ≡ ASCII codepoint sort for kebab slugs),
 * byte-exact to `render-node-appset.sh`'s per-env `render_kustomization`.
 */
function renderKustomization(env: string, nodes: Set<string>): string {
  const lines = [APPSETS_KUSTOMIZATION_HEADER];
  for (const node of [...nodes].sort()) {
    lines.push(`  - ${env}-${node}-applicationset.yaml`);
  }
  // Trailing newline matches the shell renderer's final printf line.
  return `${lines.join("\n")}\n`;
}

/**
 * Fold `<slug>` into ONE env's `appsets/<env>/kustomization.yaml`, then re-render the WHOLE file
 * node-sorted, byte-exact to `render-node-appset.sh`'s per-env `render_kustomization`. Each env's
 * kustomization is self-contained (generated wholesale) — there is no all-envs sentinel-splice anymore.
 * Idempotent.
 */
export function insertAppsetKustomization(
  currentKustomization: string,
  slug: string,
  env: string
): string {
  const lines = currentKustomization.split("\n");
  const resourcesIdx = lines.indexOf("resources:");
  if (resourcesIdx === -1) {
    throw new Error(
      `infra/k8s/argocd/appsets/${env}/kustomization.yaml is missing a 'resources:' list; cannot fold in the slug.`
    );
  }

  const nodes = existingNodes(lines.slice(resourcesIdx + 1), env);
  if (nodes.has(slug)) {
    return currentKustomization;
  }
  nodes.add(slug);

  return renderKustomization(env, nodes);
}
