// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/appset`
 * Purpose: Pin `renderNodeAppset` + `insertAppsetKustomization` to byte-exact cases mirroring
 *   `scripts/ci/render-node-appset.sh` (template sed-substitution + the WHOLE per-env
 *   appsets/<env>/kustomization.yaml render_kustomization output).
 * Scope: Pure unit tests — goldens mirror the shell renderer's output so the operator's emit can't skew
 *   against the `pnpm gen:node-appset --check` drift gate.
 * Invariants: BYTE_EXACT_WITH_RENDERER — token substitution + env-major/node-sorted whole-file ordering.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/appset, scripts/ci/render-node-appset.sh
 * @public
 */

import { describe, expect, it } from "vitest";

import {
  insertAppsetKustomization,
  removeFromAppsetsKustomization,
  renderNodeAppset,
} from "./appset";

// Minimal template carrying both tokens + an Argo goTemplate marker that must survive untouched.
const TEMPLATE = `metadata:
  name: cogni-__ENV__-__NODE__
spec:
  generators:
    - git:
        revision: deploy/__ENV__-__NODE__
        files:
          - path: "infra/catalog/__NODE__.yaml"
  template:
    metadata:
      name: "__ENV__-{{.name}}"
`;

// The GENERATED per-env appsets/<env>/kustomization.yaml header — byte-exact to render-node-appset.sh's
// per-env render_kustomization heredoc (everything up to and including `resources:`).
const HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../control-plane/<env>/<env>-appsets-application.yaml).
# One AppSet per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

// A whole candidate-a appsets/candidate-a/kustomization.yaml listing canary/node-template/operator.
// Each per-env kustomization is self-contained (only ITS env's nodes); the full <env>- filename prefix
// is kept on disk even though the file is nested under <env>/.
const BEFORE = `${HEADER}
  - candidate-a-canary-applicationset.yaml
  - candidate-a-node-template-applicationset.yaml
  - candidate-a-operator-applicationset.yaml
`;

describe("renderNodeAppset", () => {
  it("substitutes __ENV__/__NODE__ globally and leaves {{.name}} intact", () => {
    expect(renderNodeAppset(TEMPLATE, "foo", "candidate-a")).toBe(
      `metadata:
  name: cogni-candidate-a-foo
spec:
  generators:
    - git:
        revision: deploy/candidate-a-foo
        files:
          - path: "infra/catalog/foo.yaml"
  template:
    metadata:
      name: "candidate-a-{{.name}}"
`
    );
  });
});

describe("insertAppsetKustomization", () => {
  it("folds the new slug into the env's resources in ASCII-sorted position, re-rendering the whole file", () => {
    // 'foo' sorts between 'canary' and 'node-template' in candidate-a's node-set.
    expect(insertAppsetKustomization(BEFORE, "foo", "candidate-a")).toBe(
      `${HEADER}
  - candidate-a-canary-applicationset.yaml
  - candidate-a-foo-applicationset.yaml
  - candidate-a-node-template-applicationset.yaml
  - candidate-a-operator-applicationset.yaml
`
    );
  });

  it("is idempotent when the slug is already listed", () => {
    const once = insertAppsetKustomization(BEFORE, "foo", "candidate-a");
    expect(insertAppsetKustomization(once, "foo", "candidate-a")).toBe(once);
  });

  it("throws when the resources list is missing", () => {
    expect(() =>
      insertAppsetKustomization("kind: Kustomization\n", "foo", "candidate-a")
    ).toThrow(/resources/);
  });

  // PER-ENV (story.5020) — each env's kustomization is self-contained, so folding a
  // slug into one env never touches another env's file. A node born into a subset of
  // envs simply has insertAppsetKustomization called once per birth env on that env's
  // own file; an env it was NOT born into is never passed here, so it stays untouched.
  it("folds into preview's own (smaller) node-set independently of candidate-a", () => {
    const PREVIEW_BEFORE = `${HEADER}
  - preview-operator-applicationset.yaml
`;
    expect(insertAppsetKustomization(PREVIEW_BEFORE, "foo", "preview")).toBe(
      `${HEADER}
  - preview-foo-applicationset.yaml
  - preview-operator-applicationset.yaml
`
    );
  });
});

describe("removeFromAppsetsKustomization", () => {
  // The decommission inverse re-renders the WHOLE file over the reduced node-set, so its output is
  // byte-exact to render-node-appset.sh on the reduced catalog (story.5020). A node listed between
  // 'canary' and 'node-template' is dropped, leaving the surrounding entries untouched + node-sorted.
  const WITH_FOO = `${HEADER}
  - candidate-a-canary-applicationset.yaml
  - candidate-a-foo-applicationset.yaml
  - candidate-a-node-template-applicationset.yaml
  - candidate-a-operator-applicationset.yaml
`;

  it("drops the slug and re-renders the whole file node-sorted", () => {
    expect(removeFromAppsetsKustomization(WITH_FOO, "foo", "candidate-a")).toBe(
      BEFORE
    );
  });

  it("round-trips with insertAppsetKustomization (byte-identity on add→remove)", () => {
    const added = insertAppsetKustomization(BEFORE, "foo", "candidate-a");
    expect(removeFromAppsetsKustomization(added, "foo", "candidate-a")).toBe(
      BEFORE
    );
  });

  it("is idempotent when the slug is not listed", () => {
    expect(
      removeFromAppsetsKustomization(BEFORE, "absent", "candidate-a")
    ).toBe(BEFORE);
  });

  it("can empty an env's resources list down to the bare header", () => {
    const SINGLETON = `${HEADER}
  - candidate-a-onlynode-applicationset.yaml
`;
    expect(
      removeFromAppsetsKustomization(SINGLETON, "onlynode", "candidate-a")
    ).toBe(`${HEADER}\n`);
  });

  it("throws when the resources list is missing", () => {
    expect(() =>
      removeFromAppsetsKustomization(
        "kind: Kustomization\n",
        "foo",
        "candidate-a"
      )
    ).toThrow(/resources/);
  });
});

// The GENERATED appsets/production-hosted-lanes/kustomization.yaml header — byte-exact to
// render-node-appset.sh's SECOND render_kustomization heredoc.
const HOSTED_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2026 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# Per-(env, node) ApplicationSets the PRODUCTION cluster reconciles on ANOTHER env's behalf —
# the akash+crossplane lanes (story.5016 seam 3). Applied with prune by the
# cogni-production-hosted-lane-appsets app-of-apps
# (../../control-plane/production/production-hosted-lane-appsets-application.yaml).
# Each AppSet is byte-identical to the one its own env would have rendered; only the
# app-of-apps that applies it differs. Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

/**
 * story.5016 seam 3. The hosted-lane directory is the one appsets directory that legitimately holds
 * cells from MORE THAN ONE environment, which is why the kustomization is modelled as a set of file
 * names rather than node slugs. These cases pin that: a candidate-a entry and a preview entry must
 * coexist, sort by file name, and survive a round-trip — the old node-slug model would have dropped
 * whichever env did not match the directory name.
 */
describe("hosted-lane appsets directory (story.5016 seam 3)", () => {
  const HOSTED_DIR = "production-hosted-lanes";

  it("emits the hosted-lane header and keeps cells from two envs", () => {
    const withCandidate = insertAppsetKustomization(
      `${HOSTED_HEADER}\n`,
      "poly",
      "candidate-a",
      HOSTED_DIR
    );
    const withBoth = insertAppsetKustomization(
      withCandidate,
      "poly",
      "preview",
      HOSTED_DIR
    );
    expect(withBoth).toBe(`${HOSTED_HEADER}
  - candidate-a-poly-applicationset.yaml
  - preview-poly-applicationset.yaml
`);
  });

  it("removes only the named (env, slug) cell, leaving the other env's lane", () => {
    const both = `${HOSTED_HEADER}
  - candidate-a-poly-applicationset.yaml
  - preview-poly-applicationset.yaml
`;
    expect(
      removeFromAppsetsKustomization(both, "poly", "candidate-a", HOSTED_DIR)
    ).toBe(`${HOSTED_HEADER}
  - preview-poly-applicationset.yaml
`);
  });

  it("renders a hosted lane's AppSet body identically to its own env's render", () => {
    // ONLY_DELIVERY_MOVED: the directory changes, the object does not. `renderNodeAppset` takes no
    // directory at all, which is the structural guarantee — there is no seam through which a
    // hosted lane's body could diverge from the one its own env would have produced.
    expect(renderNodeAppset(TEMPLATE, "poly", "candidate-a")).toContain(
      "revision: deploy/candidate-a-poly"
    );
  });

  it("leaves the per-env directory on the unchanged env header", () => {
    expect(insertAppsetKustomization(BEFORE, "foo", "candidate-a")).toContain(
      "cogni-<env>-appsets app-of-apps"
    );
  });
});
