// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/appset`
 * Purpose: Pure port of `scripts/ci/render-node-appset.sh` — emit a new node's per-`(env, slug)` Argo
 *   ApplicationSet objects and the PER-ENV `infra/k8s/argocd/appsets/<env>/kustomization.yaml` that lists
 *   that env's AppSets, so the operator can author a node-formation PR without bash. One AppSet object per
 *   `(env, node)` is the structural LANE_ISOLATION fix (`bug.0378`): a flight only ever applies its own
 *   node's file. Each appsets/<env>/ dir is reconciled with prune by its OWN per-env `cogni-<env>-appsets`
 *   app-of-apps, so a catalog-removed node's AppSet auto-prunes once its file leaves git — and no foreign
 *   env's AppSets ever fan onto a cluster (story.5020).
 * Scope: `renderNodeAppset` substitutes the shared template (the SAME file the shell renderer feeds, so
 *   output is byte-exact and the `--check` drift gate stays green); `insertAppsetKustomization` rebuilds
 *   the WHOLE `appsets/<dir>/kustomization.yaml` for ONE directory with the new slug folded in
 *   (file-name-sorted, mirroring the shell's `render_kustomization`). The old all-envs single
 *   kustomization is GONE — each directory has its own self-contained kustomization generated wholesale.
 *
 *   `<dir>` is USUALLY the cell's own environment, but an akash+crossplane pre-prod lane is reconciled
 *   by the PRODUCTION cluster and therefore renders into `appsets/production-hosted-lanes/`
 *   (story.5016 seam 3 — see `@shared/node-registry/akash-lane-host`). The AppSet BODY is identical
 *   either way; only the directory, and so the app-of-apps that applies it, differs. That is why the
 *   kustomization is modelled as a set of FILE NAMES rather than a set of node slugs: the hosted-lane
 *   directory legitimately holds files from more than one environment.
 * Invariants: BYTE_EXACT_WITH_RENDERER — token substitution + per-directory whole-file ordering match
 *   `render-node-appset.sh`. For an env directory the `<env>-` prefix is constant, so sorting file names
 *   is the same order as sorting node slugs and every committed env kustomization is unchanged.
 *   IDEMPOTENT — a kustomization already listing the slug is returned unchanged.
 * Side-effects: none — pure string transforms, no IO, no env.
 * Links: scripts/ci/render-node-appset.sh, scripts/ci/node-applicationset.yaml.tmpl,
 *   src/shared/node-registry/akash-lane-host.ts, bug.0378, task.5092, story.5020, story.5016
 * @public
 */

import { HOSTED_LANE_APPSETS_DIR } from "@/shared/node-registry/akash-lane-host";

/**
 * The literal header of a GENERATED `infra/k8s/argocd/appsets/<env>/kustomization.yaml`, byte-exact to the
 * shell renderer's `render_kustomization` heredoc (everything up to and including the `resources:` line).
 */
const ENV_APPSETS_KUSTOMIZATION_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../control-plane/<env>/<env>-appsets-application.yaml).
# One AppSet per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

/**
 * The header of the GENERATED `appsets/production-hosted-lanes/kustomization.yaml` — the lanes the
 * PRODUCTION cluster reconciles on another environment's behalf (story.5016 seam 3). A separate
 * literal, byte-exact to the shell renderer's second heredoc, so the env-directory header above stays
 * unchanged and every committed env kustomization is untouched by seam 3.
 */
const HOSTED_LANE_APPSETS_KUSTOMIZATION_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2026 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# Per-(env, node) ApplicationSets the PRODUCTION cluster reconciles on ANOTHER env's behalf —
# the akash+crossplane lanes (story.5016 seam 3). Applied with prune by the
# cogni-production-hosted-lane-appsets app-of-apps
# (../../control-plane/production/production-hosted-lane-appsets-application.yaml).
# Each AppSet is byte-identical to the one its own env would have rendered; only the
# app-of-apps that applies it differs. Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

/** The `resources:` header for one appsets directory. */
function kustomizationHeader(dir: string): string {
  return dir === HOSTED_LANE_APPSETS_DIR
    ? HOSTED_LANE_APPSETS_KUSTOMIZATION_HEADER
    : ENV_APPSETS_KUSTOMIZATION_HEADER;
}

/**
 * The ApplicationSet file name for one `(env, slug)` cell. Identical in every directory — the file
 * NAME encodes the lane, the DIRECTORY encodes the reconciling cluster.
 */
export function appsetFileName(env: string, slug: string): string {
  return `${env}-${slug}-applicationset.yaml`;
}

/**
 * Substitute the per-`(env, slug)` ApplicationSet template, byte-exact to the shell renderer's
 * `sed -e s/__ENV__/…/g -e s/__NODE__/…/g`. Argo `{{.name}}` goTemplate markers are left intact.
 */
export function renderNodeAppset(
  template: string,
  slug: string,
  env: string
): string {
  return template.replaceAll("__ENV__", env).replaceAll("__NODE__", slug);
}

/**
 * Parse the resources list of ONE `appsets/<dir>/kustomization.yaml` into its FILE set. Each resource
 * line is `<env>-<node>-applicationset.yaml`; the full `<env>-` prefix is kept on disk even in an env
 * directory. Keeping whole file names (rather than stripping back to a node slug) is what lets the
 * hosted-lane directory hold cells from more than one environment without silently dropping them.
 */
function existingFiles(resourceLines: readonly string[]): Set<string> {
  const files = new Set<string>();
  for (const line of resourceLines) {
    const file = line.match(/^ {2}- (.+-applicationset\.yaml)$/)?.[1];
    if (file === undefined) continue;
    files.add(file);
  }
  return files;
}

/**
 * Render the WHOLE `appsets/<dir>/kustomization.yaml` (header + apiVersion + kind + namespace + resources)
 * for ONE directory from its file set, file-name-sorted (LC_ALL=C order ≡ ASCII codepoint sort for kebab
 * names), byte-exact to `render-node-appset.sh`'s `render_kustomization`.
 */
function renderKustomization(dir: string, files: Set<string>): string {
  const lines = [kustomizationHeader(dir)];
  for (const file of [...files].sort()) {
    lines.push(`  - ${file}`);
  }
  // Trailing newline matches the shell renderer's final printf line.
  return `${lines.join("\n")}\n`;
}

/**
 * Fold the `(env, slug)` cell into ONE directory's `appsets/<dir>/kustomization.yaml`, then re-render the
 * WHOLE file file-name-sorted, byte-exact to `render-node-appset.sh`'s `render_kustomization`. Each
 * directory's kustomization is self-contained (generated wholesale) — there is no all-envs
 * sentinel-splice anymore. Idempotent.
 *
 * `dir` defaults to `env`, which is the answer for every k3s row, every legacy-authority akash row and
 * every production row. A caller that has resolved the cell to a production-hosted Akash lane passes
 * {@link HOSTED_LANE_APPSETS_DIR} instead; `env` still selects the FILE NAME, so the lane keeps its own
 * identity.
 */
export function insertAppsetKustomization(
  currentKustomization: string,
  slug: string,
  env: string,
  dir: string = env
): string {
  const lines = currentKustomization.split("\n");
  const resourcesIdx = lines.indexOf("resources:");
  if (resourcesIdx === -1) {
    throw new Error(
      `infra/k8s/argocd/appsets/${dir}/kustomization.yaml is missing a 'resources:' list; cannot fold in the slug.`
    );
  }

  const files = existingFiles(lines.slice(resourcesIdx + 1));
  const file = appsetFileName(env, slug);
  if (files.has(file)) {
    return currentKustomization;
  }
  files.add(file);

  return renderKustomization(dir, files);
}

/**
 * Drop `<slug>` from ONE env's `appsets/<env>/kustomization.yaml`, then re-render the WHOLE file
 * node-sorted — the inverse of {@link insertAppsetKustomization}. Because it re-runs the same
 * {@link renderKustomization} over the reduced node-set, the output is byte-exact to what
 * `render-node-appset.sh` emits for that reduced catalog, so the `--check` drift gate stays green on
 * a decommission (story.5020). Idempotent: a kustomization that does not list the slug is unchanged.
 */
export function removeFromAppsetsKustomization(
  currentKustomization: string,
  slug: string,
  env: string,
  dir: string = env
): string {
  const lines = currentKustomization.split("\n");
  const resourcesIdx = lines.indexOf("resources:");
  if (resourcesIdx === -1) {
    throw new Error(
      `infra/k8s/argocd/appsets/${dir}/kustomization.yaml is missing a 'resources:' list; cannot drop the slug.`
    );
  }

  const files = existingFiles(lines.slice(resourcesIdx + 1));
  const file = appsetFileName(env, slug);
  if (!files.has(file)) {
    return currentKustomization;
  }
  files.delete(file);

  return renderKustomization(dir, files);
}
