// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2026 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/env-membership-plan`
 * Purpose: Pin the pure env-delta planner — add-env inserts, remove-env sha:null deletions +
 *   regenerated kustomization, and the ATOMIC_PER_ENV + idempotency invariants. Every env is an
 *   independent toggle while the non-empty deploy set and singleton activity authority remain valid.
 * Scope: Pure unit tests over hand-built control-plane fixtures (no Octokit).
 * Invariants: ATOMIC_PER_ENV, IDEMPOTENT, DELETE_VIA_SHA_NULL, TEMPLATE_OVERLAY_IS_RENDER_SOURCE,
 *   OPERATOR_SELF_HOSTS_THE_VERB.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/env-membership-plan
 * @public
 */

import { describe, expect, it } from "vitest";

import {
  appsetPath,
  appsetsKustomizationPath,
  buildEnvDeltaPlan,
  buildPlacementPlan,
  CATALOG_PATH,
  type EnvDeltaResult,
  type EnvPlanCurrent,
  EnvPlanError,
  type EnvPlanOp,
  externalSecretPath,
  overlayPath,
} from "./env-membership-plan";

const SLUG = "blue";

const KUST_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../<env>-appsets-application.yaml). One AppSet
# per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

const kustWith = (env: string, nodes: readonly string[]): string =>
  `${KUST_HEADER}\n${nodes
    .map((n) => `  - ${env}-${n}-applicationset.yaml`)
    .join("\n")}\n`;

// node-template overlay carrying the node-at-root migrate command renderOverlay requires.
const TEMPLATE_OVERLAY = `namespace: cogni-candidate-a-node-template
resources:
  - ../../../base/node-app
patches:
  - target: { kind: Service }
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30200
images:
  - name: node-app
    newName: ghcr.io/cogni-dao/cogni-template-node-template
initContainers:
  migrate: exec node /app/app/migrate.mjs /app/app/migrations
`;

// node-template overlay's external-secret.yaml (the ESO producer). renderOverlayFile only
// slug/port-renames it — node-template → blue everywhere, no migrate guard.
const TEMPLATE_EXTERNAL_SECRET = `apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  labels:
    app.kubernetes.io/component: node-template
spec:
  target:
    name: node-template-env-secrets
  dataFrom:
    - extract:
        key: candidate-a/node-template
`;

const APPSET_TEMPLATE = `metadata:
  name: cogni-__ENV__-__NODE__
spec:
  generators:
    - git:
        files:
          - path: "infra/catalog/__NODE__.yaml"
`;

const catalogWith = (envs: readonly string[]): string =>
  `name: ${SLUG}
type: node
port: 3200
node_port: 31100
dockerfile: nodes/${SLUG}/app/Dockerfile
image_tag_suffix: "-${SLUG}"
migrator_tag_suffix: "-${SLUG}-migrate"
candidate_a_branch: deploy/candidate-a-${SLUG}
preview_branch: deploy/preview-${SLUG}
production_branch: deploy/production-${SLUG}
envs: [${envs.join(", ")}]
activity_env: ${envs[0] ?? "candidate-a"}
path_prefix: nodes/${SLUG}/
`;

function baseCurrent(envs: readonly string[]): EnvPlanCurrent {
  const appsetsKustomizationByEnv: Record<string, string> = {};
  const templateOverlayByEnv: Record<string, string> = {};
  const templateExternalSecretByEnv: Record<string, string> = {};
  for (const e of envs) {
    appsetsKustomizationByEnv[e] = kustWith(e, ["blue", "operator"]);
    templateOverlayByEnv[e] = TEMPLATE_OVERLAY;
    templateExternalSecretByEnv[e] = TEMPLATE_EXTERNAL_SECRET;
  }
  // preview is an env we ADD in tests, so make its template overlay + kustomization available.
  appsetsKustomizationByEnv.preview ??= kustWith("preview", ["operator"]);
  templateOverlayByEnv.preview ??= TEMPLATE_OVERLAY;
  templateExternalSecretByEnv.preview ??= TEMPLATE_EXTERNAL_SECRET;
  return {
    catalog: catalogWith(envs),
    templateOverlayByEnv,
    templateExternalSecretByEnv,
    appsetTemplate: APPSET_TEMPLATE,
    appsetsKustomizationByEnv,
    port: 3200,
    nodePort: 31100,
  };
}

const paths = (ops: readonly EnvPlanOp[]): string[] => ops.map((o) => o.path);
const deletes = (ops: readonly EnvPlanOp[]): string[] =>
  ops.filter((o) => o.op === "delete").map((o) => o.path);

describe("buildEnvDeltaPlan — ADD env", () => {
  it("inserts catalog edit + overlay + appset + kustomization fold for the added env", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a"]),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // No deletes on an add.
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH(SLUG),
        overlayPath("preview", SLUG),
        externalSecretPath("preview", SLUG),
        appsetPath("preview", SLUG),
        appsetsKustomizationPath("preview"),
      ].sort()
    );
    // ESO producer is cloned with the slug rename applied.
    const esOp = res.ops.find(
      (o) => o.path === externalSecretPath("preview", SLUG)
    );
    expect(esOp?.op).toBe("upsert");
    if (esOp?.op === "upsert") {
      expect(esOp.content).toContain("name: blue-env-secrets");
      expect(esOp.content).not.toContain("node-template");
    }

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    // Overlay rename applied (node-template → blue).
    const overlayOp = res.ops.find(
      (o) => o.path === overlayPath("preview", SLUG)
    );
    if (overlayOp?.op === "upsert") {
      expect(overlayOp.content).toContain("cogni-candidate-a-blue");
    }
    // appsets kustomization now lists blue under preview.
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("preview")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).toContain("preview-blue-applicationset.yaml");
    }
  });

  it("is idempotent when the env is already present", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — REMOVE env (partial)", () => {
  it("drops the env line + sha:null deletes overlay+appset + regenerates kustomization", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // Overlay + appset are DELETED (sha:null in the adapter).
    expect(deletes(res.ops).sort()).toEqual(
      [
        overlayPath("production", SLUG),
        externalSecretPath("production", SLUG),
        appsetPath("production", SLUG),
      ].sort()
    );
    // Catalog edited + kustomization regenerated without blue.
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("production")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "production-blue-applicationset.yaml"
      );
    }
    // The catalog row itself is NEVER deleted on a remove (per-node state stays).
    expect(deletes(res.ops)).not.toContain(CATALOG_PATH(SLUG));
  });

  it("is idempotent when the env is already absent", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — safe removals", () => {
  it("rejects removing the current activity authority even when other deployments survive", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a", "preview", "production"]),
      });

    expect(call).toThrowError(
      expect.objectContaining({
        code: "activity_authority_cutover_required",
        status: 422,
      })
    );
  });

  it("rejects removing the LAST remaining environment", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a"]),
      });

    expect(call).toThrowError(
      expect.objectContaining({
        code: "final_environment_required",
        status: 422,
      })
    );
  });

  it("is idempotent both directions on candidate-a (add already-present / remove already-absent)", () => {
    // add candidate-a when already present → no_changes
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: true,
        current: baseCurrent(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
    // remove candidate-a when already absent → no_changes (no authority mutation is attempted)
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["preview"]),
      }).kind
    ).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — TEMPLATE_OVERLAY_IS_RENDER_SOURCE", () => {
  // node-template's real catalog row: template port literals (3200/30200), production authority.
  const templateCatalogWith = (envs: readonly string[]): string =>
    `name: node-template
type: node
port: 3200
node_port: 30200
dockerfile: nodes/node-template/app/Dockerfile
envs: [${envs.join(", ")}]
activity_env: production
path_prefix: nodes/node-template/
`;

  const templateCurrent = (envs: readonly string[]): EnvPlanCurrent => {
    const appsetsKustomizationByEnv: Record<string, string> = {};
    const templateOverlayByEnv: Record<string, string> = {};
    const templateExternalSecretByEnv: Record<string, string> = {};
    for (const e of ["candidate-a", "preview", "production"]) {
      appsetsKustomizationByEnv[e] = kustWith(e, [
        "blue",
        "node-template",
        "operator",
      ]);
      templateOverlayByEnv[e] = TEMPLATE_OVERLAY;
      templateExternalSecretByEnv[e] = TEMPLATE_EXTERNAL_SECRET;
    }
    return {
      catalog: templateCatalogWith(envs),
      templateOverlayByEnv,
      templateExternalSecretByEnv,
      appsetTemplate: APPSET_TEMPLATE,
      appsetsKustomizationByEnv,
      port: 3200,
      nodePort: 30200,
    };
  };

  it("removes node-template's DEPLOYMENT but keeps its overlay files (the render template)", () => {
    const res = buildEnvDeltaPlan({
      slug: "node-template",
      env: "candidate-a",
      present: false,
      current: templateCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["preview", "production"]);
    // REDUCED delete set: ONLY the appset leaves git.
    expect(deletes(res.ops)).toEqual([
      appsetPath("candidate-a", "node-template"),
    ]);
    // The overlay files are NOT touched at all (no delete, no upsert).
    expect(paths(res.ops)).not.toContain(
      overlayPath("candidate-a", "node-template")
    );
    expect(paths(res.ops)).not.toContain(
      externalSecretPath("candidate-a", "node-template")
    );
    // Catalog env dropped + kustomization regenerated without node-template.
    const catalogOp = res.ops.find(
      (o) => o.path === CATALOG_PATH("node-template")
    );
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [preview, production]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("candidate-a")
    );
    expect(kustOp?.op).toBe("upsert");
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "candidate-a-node-template-applicationset.yaml"
      );
      expect(kustOp.content).toContain("candidate-a-blue-applicationset.yaml");
    }
  });

  it("still refuses to remove node-template's activity authority (production)", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: "node-template",
        env: "production",
        present: false,
        current: templateCurrent(["candidate-a", "preview", "production"]),
      });
    expect(call).toThrowError(
      expect.objectContaining({
        code: "activity_authority_cutover_required",
        status: 422,
      })
    );
  });

  it("re-adds node-template as an ordinary add (overlay files already in tree are the source)", () => {
    const res = buildEnvDeltaPlan({
      slug: "node-template",
      env: "candidate-a",
      present: true,
      current: templateCurrent(["preview", "production"]),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview", "production"]);
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH("node-template"),
        overlayPath("candidate-a", "node-template"),
        externalSecretPath("candidate-a", "node-template"),
        appsetPath("candidate-a", "node-template"),
        appsetsKustomizationPath("candidate-a"),
      ].sort()
    );
    // Rendering the template with its own slug + its own port literals is the identity
    // transform — the re-added overlay is byte-identical to the render source.
    const overlayOp = res.ops.find(
      (o) => o.path === overlayPath("candidate-a", "node-template")
    );
    expect(overlayOp?.op).toBe("upsert");
    if (overlayOp?.op === "upsert") {
      expect(overlayOp.content).toBe(TEMPLATE_OVERLAY);
    }
    // Authority stays production (max of nextEnvs) — the add cannot demote it.
    const catalogOp = res.ops.find(
      (o) => o.path === CATALOG_PATH("node-template")
    );
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("activity_env: production");
    }
  });

  it("is idempotent adding node-template to an env it already claims", () => {
    expect(
      buildEnvDeltaPlan({
        slug: "node-template",
        env: "candidate-a",
        present: true,
        current: templateCurrent(["candidate-a", "preview", "production"]),
      }).kind
    ).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — OPERATOR_SELF_HOSTS_THE_VERB", () => {
  it("refuses to remove operator from any env (the control plane cannot undeploy itself)", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: "operator",
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a", "preview", "production"]),
      });
    expect(call).toThrow(EnvPlanError);
    try {
      call();
      throw new Error("expected EnvPlanError");
    } catch (e) {
      expect(e).toBeInstanceOf(EnvPlanError);
      expect((e as EnvPlanError).code).toBe("operator_node_immutable");
      expect((e as EnvPlanError).status).toBe(422);
    }
  });
});

describe("ACTIVITY_FOLLOWS_INGEST (bug.5079)", () => {
  const catalogOf = (plan: EnvDeltaResult): string => {
    if (!("ops" in plan)) return "";
    for (const op of plan.ops) {
      if (op.op === "upsert" && op.path.includes("infra/catalog/")) {
        return op.content;
      }
    }
    return "";
  };

  /** baseCurrent seeds templates only for the given envs (+preview); production needs its own. */
  const currentWithProduction = (envs: readonly string[]): EnvPlanCurrent => {
    const base = baseCurrent(envs);
    return {
      ...base,
      templateOverlayByEnv: {
        ...base.templateOverlayByEnv,
        production: TEMPLATE_OVERLAY,
      },
      templateExternalSecretByEnv: {
        ...base.templateExternalSecretByEnv,
        production: TEMPLATE_EXTERNAL_SECRET,
      },
      appsetsKustomizationByEnv: {
        ...base.appsetsKustomizationByEnv,
        production: kustWith("production", ["operator"]),
      },
    };
  };

  it("promoting candidate-a → production moves the activity authority with it", () => {
    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: true,
      current: currentWithProduction(["candidate-a"]),
    });

    // Without this, the node deploys and serves in production while its webhooks — which
    // GitHub delivers to production ONLY — are dropped `unclaimed`, silently, forever.
    expect(catalogOf(plan)).toContain("activity_env: production");
    expect(catalogOf(plan)).not.toContain("activity_env: candidate-a");
  });

  it("promoting to preview moves authority up from candidate-a", () => {
    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a"]),
    });

    expect(catalogOf(plan)).toContain("activity_env: preview");
  });

  it("carries a trailing comment across the activity_env rewrite", () => {
    // ACTIVITY_ENV_LINE_RE matches the trailing comment, so a naive whole-line replace
    // deletes it. These rows carry load-bearing comments and a silent drop in a generated
    // PR is exactly what nobody notices.
    const base = baseCurrent(["candidate-a"]);
    const current = {
      ...currentWithProduction(["candidate-a"]),
      catalog: base.catalog.replace(
        "activity_env: candidate-a",
        "activity_env: candidate-a # birth authority, moves on promotion"
      ),
    };

    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: true,
      current,
    });

    expect(catalogOf(plan)).toContain(
      "activity_env: production # birth authority, moves on promotion"
    );
  });

  it("takes the HIGHEST deployed env, not just the one being added", () => {
    // The subtle case my first rule got wrong: this node is already in production, and
    // adding `preview` must not pull its authority DOWN to preview — preview cannot ingest
    // either. Authority is max(nextEnvs), which is monotonic by construction.
    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: currentWithProduction(["candidate-a", "production"]),
    });

    expect(catalogOf(plan)).toContain("activity_env: production");
    expect(catalogOf(plan)).not.toContain("activity_env: preview");
  });
});

// ── Placement lever (story.5016 T5) ─────────────────────────────────────────────────────────────

/** baseCurrent with an external build plane (source_repo) — akash's eligibility precondition. */
const externallyBuilt = (envs: readonly string[]): EnvPlanCurrent => {
  const base = baseCurrent(envs);
  return {
    ...base,
    catalog: base.catalog.replace(
      "envs: [",
      `source_repo: https://github.com/cogni-dao/${SLUG}.git\nimage_repository: ghcr.io/cogni-dao/${SLUG}\nenvs: [`
    ),
  };
};

const K3S_LANE_PATHS = (env: string): string[] => [
  overlayPath(env, SLUG),
  externalSecretPath(env, SLUG),
  appsetPath(env, SLUG),
];

describe("buildPlacementPlan — akash", () => {
  it("upserts deployment_provider + emits the SAME k3s-lane deletes an env remove does", () => {
    const res = buildPlacementPlan({
      slug: SLUG,
      env: "preview",
      placement: "akash",
      current: externallyBuilt(["candidate-a", "preview"]),
      existingK3sPaths: K3S_LANE_PATHS("preview"),
    });
    expect(res.kind).toBe("place_akash");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(deletes(res.ops).sort()).toEqual(K3S_LANE_PATHS("preview").sort());
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain(
        "deployment_provider:\n  preview: akash"
      );
      // envs: reach is untouched — placement is a lane switch, not an undeploy.
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
      // compute_egress_cidrs (absent here) and every other line pass through unchanged.
      expect(catalogOp.content).toContain("source_repo:");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("preview")
    );
    expect(kustOp?.op).toBe("upsert");
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain("preview-blue-applicationset.yaml");
    }
  });

  it("limits deletes to paths that exist on main (trees API 422s on sha:null for a missing path)", () => {
    const res = buildPlacementPlan({
      slug: SLUG,
      env: "preview",
      placement: "akash",
      current: externallyBuilt(["candidate-a", "preview"]),
      existingK3sPaths: [overlayPath("preview", SLUG)],
    });
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");
    expect(deletes(res.ops)).toEqual([overlayPath("preview", SLUG)]);
  });

  it("already-akash with lingering overlays emits JUST the cleanup (toks4 normalization path)", () => {
    const base = externallyBuilt(["candidate-a", "preview"]);
    const current = {
      ...base,
      catalog: base.catalog.replace(
        "envs: [candidate-a, preview]\n",
        "envs: [candidate-a, preview]\ndeployment_provider:\n  preview: akash\n"
      ),
    };
    const res = buildPlacementPlan({
      slug: SLUG,
      env: "preview",
      placement: "akash",
      current,
      existingK3sPaths: K3S_LANE_PATHS("preview"),
    });
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");
    // No catalog op — the map already says akash; only the residue is removed.
    expect(res.ops.find((o) => o.path === CATALOG_PATH(SLUG))).toBeUndefined();
    expect(deletes(res.ops).sort()).toEqual(K3S_LANE_PATHS("preview").sort());
  });

  it("is idempotent: already-akash with NO residue → no_changes", () => {
    const base = externallyBuilt(["candidate-a", "preview"]);
    const current = {
      ...base,
      catalog: base.catalog.replace(
        "envs: [candidate-a, preview]\n",
        "envs: [candidate-a, preview]\ndeployment_provider:\n  preview: akash\n"
      ),
      appsetsKustomizationByEnv: {
        ...base.appsetsKustomizationByEnv,
        preview: kustWith("preview", ["operator"]), // slug already absent
      },
    };
    expect(
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "akash",
        current,
        existingK3sPaths: [],
      }).kind
    ).toBe("no_changes");
  });

  it("refuses akash for a node without source_repo (no external build plane)", () => {
    const call = () =>
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "akash",
        current: baseCurrent(["candidate-a", "preview"]),
        existingK3sPaths: K3S_LANE_PATHS("preview"),
      });
    expect(call).toThrowError(
      expect.objectContaining({
        code: "akash_requires_source_repo",
        status: 422,
      })
    );
  });

  it("refuses placement for an env the node is not deployed to", () => {
    const call = () =>
      buildPlacementPlan({
        slug: SLUG,
        env: "production",
        placement: "akash",
        current: externallyBuilt(["candidate-a"]),
        existingK3sPaths: [],
      });
    expect(call).toThrowError(
      expect.objectContaining({ code: "env_not_deployed", status: 422 })
    );
  });

  it("refuses to move operator off k3s (it is the control plane serving this verb)", () => {
    const call = () =>
      buildPlacementPlan({
        slug: "operator",
        env: "candidate-a",
        placement: "akash",
        current: externallyBuilt(["candidate-a"]),
        existingK3sPaths: [],
      });
    expect(call).toThrowError(
      expect.objectContaining({ code: "operator_node_immutable", status: 422 })
    );
  });

  it("places node-template on akash like an ordinary node, but with the REDUCED delete set (only the appset leaves)", () => {
    // node-template's real catalog row + an external build plane (akash's eligibility precondition).
    const templateCatalogWith = (envs: readonly string[]): string =>
      `name: node-template
type: node
port: 3200
node_port: 30200
dockerfile: nodes/node-template/app/Dockerfile
source_repo: https://github.com/cogni-dao/node-template.git
image_repository: ghcr.io/cogni-dao/node-template
envs: [${envs.join(", ")}]
activity_env: production
path_prefix: nodes/node-template/
`;
    const current: EnvPlanCurrent = {
      catalog: templateCatalogWith(["candidate-a"]),
      templateOverlayByEnv: { "candidate-a": TEMPLATE_OVERLAY },
      templateExternalSecretByEnv: { "candidate-a": TEMPLATE_EXTERNAL_SECRET },
      appsetTemplate: APPSET_TEMPLATE,
      appsetsKustomizationByEnv: {
        "candidate-a": kustWith("candidate-a", ["blue", "node-template"]),
      },
      port: 3200,
      nodePort: 30200,
    };
    const res = buildPlacementPlan({
      slug: "node-template",
      env: "candidate-a",
      placement: "akash",
      current,
      existingK3sPaths: [
        overlayPath("candidate-a", "node-template"),
        externalSecretPath("candidate-a", "node-template"),
        appsetPath("candidate-a", "node-template"),
      ],
    });
    expect(res.kind).toBe("place_akash");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    // REDUCED delete set: only the appset leaves git — same as an env remove.
    expect(deletes(res.ops)).toEqual([
      appsetPath("candidate-a", "node-template"),
    ]);
    // The overlay + external-secret files are NOT touched (no delete, no upsert) — they stay in
    // the tree as the render template.
    expect(paths(res.ops)).not.toContain(
      overlayPath("candidate-a", "node-template")
    );
    expect(paths(res.ops)).not.toContain(
      externalSecretPath("candidate-a", "node-template")
    );
    const catalogOp = res.ops.find(
      (o) => o.path === CATALOG_PATH("node-template")
    );
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain(
        "deployment_provider:\n  candidate-a: akash"
      );
      expect(catalogOp.content).toContain("envs: [candidate-a]");
    }
  });
});

describe("buildPlacementPlan — k3s restore", () => {
  const akashCurrent = (): EnvPlanCurrent => {
    const base = externallyBuilt(["candidate-a", "preview"]);
    return {
      ...base,
      catalog: base.catalog.replace(
        "envs: [candidate-a, preview]\n",
        "envs: [candidate-a, preview]\ndeployment_provider:\n  preview: akash\n"
      ),
      appsetsKustomizationByEnv: {
        ...base.appsetsKustomizationByEnv,
        preview: kustWith("preview", ["operator"]), // akash lane: slug absent from kustomization
      },
    };
  };

  it("drops the map entry and restores planAdd's render set (overlay+ES+appset+kustomization)", () => {
    const res = buildPlacementPlan({
      slug: SLUG,
      env: "preview",
      placement: "k3s",
      current: akashCurrent(),
    });
    expect(res.kind).toBe("place_k3s");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH(SLUG),
        overlayPath("preview", SLUG),
        externalSecretPath("preview", SLUG),
        appsetPath("preview", SLUG),
        appsetsKustomizationPath("preview"),
      ].sort()
    );
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      // The emptied block is dropped entirely (k3s is the schema default).
      expect(catalogOp.content).not.toContain("deployment_provider");
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("preview")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).toContain("preview-blue-applicationset.yaml");
    }
  });

  it("is idempotent: already on the k3s default → no_changes (no restore render)", () => {
    expect(
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "k3s",
        current: externallyBuilt(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
  });

  it("k3s is allowed WITHOUT source_repo (only akash needs the external build plane)", () => {
    expect(
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "k3s",
        current: baseCurrent(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
  });
});
