// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2026 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/env-membership-plan`
 * Purpose: Pin the pure env-delta planner — add-env inserts, remove-env sha:null deletions +
 *   regenerated kustomization, and the ATOMIC_PER_ENV + idempotency invariants. Every env is an
 *   independent toggle (candidate-a is no different from preview/production); removing the last env
 *   yields a valid empty `envs: []` set.
 * Scope: Pure unit tests over hand-built control-plane fixtures (no Octokit).
 * Invariants: ATOMIC_PER_ENV, IDEMPOTENT, DELETE_VIA_SHA_NULL.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/env-membership-plan
 * @public
 */

import { describe, expect, it } from "vitest";

import {
  appsetPath,
  appsetsKustomizationPath,
  buildEnvDeltaPlan,
  CATALOG_PATH,
  type EnvPlanCurrent,
  type EnvPlanOp,
  overlayPath,
} from "./env-membership-plan";

const SLUG = "blue";

const KUST_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../<env>-appsets-application.yaml). One AppSet
# per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

const kustWith = (env: string, nodes: readonly string[]): string =>
  `${KUST_HEADER}\n${nodes
    .map((n) => `  - ${env}-${n}-applicationset.yaml`)
    .join("\n")}\n`;

// node-template overlay carrying the node-at-root migrate command renderOverlay requires.
const TEMPLATE_OVERLAY = `namespace: cogni-candidate-a-node-template
resources:
  - ../../../base/node-app
patches:
  - target: { kind: Service }
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30200
images:
  - name: node-app
    newName: ghcr.io/cogni-dao/cogni-template-node-template
initContainers:
  migrate: exec node /app/app/migrate.mjs /app/app/migrations
`;

const APPSET_TEMPLATE = `metadata:
  name: cogni-__ENV__-__NODE__
spec:
  generators:
    - git:
        files:
          - path: "infra/catalog/__NODE__.yaml"
`;

const catalogWith = (envs: readonly string[]): string =>
  `name: ${SLUG}
type: node
port: 3200
node_port: 31100
dockerfile: nodes/${SLUG}/app/Dockerfile
image_tag_suffix: "-${SLUG}"
migrator_tag_suffix: "-${SLUG}-migrate"
candidate_a_branch: deploy/candidate-a-${SLUG}
preview_branch: deploy/preview-${SLUG}
production_branch: deploy/production-${SLUG}
envs: [${envs.join(", ")}]
path_prefix: nodes/${SLUG}/
`;

function baseCurrent(envs: readonly string[]): EnvPlanCurrent {
  const appsetsKustomizationByEnv: Record<string, string> = {};
  const templateOverlayByEnv: Record<string, string> = {};
  for (const e of envs) {
    appsetsKustomizationByEnv[e] = kustWith(e, ["blue", "operator"]);
    templateOverlayByEnv[e] = TEMPLATE_OVERLAY;
  }
  // preview is an env we ADD in tests, so make its template overlay + kustomization available.
  appsetsKustomizationByEnv.preview ??= kustWith("preview", ["operator"]);
  templateOverlayByEnv.preview ??= TEMPLATE_OVERLAY;
  return {
    catalog: catalogWith(envs),
    templateOverlayByEnv,
    appsetTemplate: APPSET_TEMPLATE,
    appsetsKustomizationByEnv,
    port: 3200,
    nodePort: 31100,
  };
}

const paths = (ops: readonly EnvPlanOp[]): string[] => ops.map((o) => o.path);
const deletes = (ops: readonly EnvPlanOp[]): string[] =>
  ops.filter((o) => o.op === "delete").map((o) => o.path);

describe("buildEnvDeltaPlan — ADD env", () => {
  it("inserts catalog edit + overlay + appset + kustomization fold for the added env", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a"]),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // No deletes on an add.
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH(SLUG),
        overlayPath("preview", SLUG),
        appsetPath("preview", SLUG),
        appsetsKustomizationPath("preview"),
      ].sort()
    );

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    // Overlay rename applied (node-template → blue).
    const overlayOp = res.ops.find(
      (o) => o.path === overlayPath("preview", SLUG)
    );
    if (overlayOp?.op === "upsert") {
      expect(overlayOp.content).toContain("cogni-candidate-a-blue");
    }
    // appsets kustomization now lists blue under preview.
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("preview")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).toContain("preview-blue-applicationset.yaml");
    }
  });

  it("is idempotent when the env is already present", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — REMOVE env (partial)", () => {
  it("drops the env line + sha:null deletes overlay+appset + regenerates kustomization", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // Overlay + appset are DELETED (sha:null in the adapter).
    expect(deletes(res.ops).sort()).toEqual(
      [overlayPath("production", SLUG), appsetPath("production", SLUG)].sort()
    );
    // Catalog edited + kustomization regenerated without blue.
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("production")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "production-blue-applicationset.yaml"
      );
    }
    // The catalog row itself is NEVER deleted on a remove (per-node state stays).
    expect(deletes(res.ops)).not.toContain(CATALOG_PATH(SLUG));
  });

  it("is idempotent when the env is already absent", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — ATOMIC_PER_ENV (candidate-a is not special)", () => {
  it("removing candidate-a is a normal atomic remove (not a decommission) — others survive", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    // Just candidate-a's env is dropped; preview + production remain.
    expect(res.nextEnvs).toEqual(["preview", "production"]);
    // Only candidate-a's overlay + appset are deleted; the catalog row survives.
    expect(deletes(res.ops).sort()).toEqual(
      [overlayPath("candidate-a", SLUG), appsetPath("candidate-a", SLUG)].sort()
    );
    expect(deletes(res.ops)).not.toContain(CATALOG_PATH(SLUG));
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [preview, production]");
    }
  });

  it("removing the LAST remaining env yields a valid empty `envs: []` set (deployed nowhere)", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      current: baseCurrent(["candidate-a"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual([]);
    // The catalog row is NOT deleted — the node keeps its row (+ caddy/scheduler), just deploys nowhere.
    expect(deletes(res.ops)).not.toContain(CATALOG_PATH(SLUG));
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: []");
    }
    // candidate-a's overlay + appset ARE deleted.
    expect(deletes(res.ops).sort()).toEqual(
      [overlayPath("candidate-a", SLUG), appsetPath("candidate-a", SLUG)].sort()
    );
  });

  it("is idempotent both directions on candidate-a (add already-present / remove already-absent)", () => {
    // add candidate-a when already present → no_changes
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: true,
        current: baseCurrent(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
    // remove candidate-a when already absent → no_changes
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["preview"]),
      }).kind
    ).toBe("no_changes");
  });
});
