// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2026 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/env-membership-plan`
 * Purpose: Pin the pure env-delta planner — add-env inserts, remove-env sha:null deletions +
 *   regenerated kustomization, full-decommission (catalog + caddy + scheduler) deletes, and the
 *   CANDIDATE_A_ALWAYS refusal + idempotency.
 * Scope: Pure unit tests over hand-built control-plane fixtures (no Octokit).
 * Invariants: CANDIDATE_A_ALWAYS, IDEMPOTENT, DELETE_VIA_SHA_NULL.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/env-membership-plan
 * @public
 */

import { describe, expect, it } from "vitest";

import {
  appsetPath,
  appsetsKustomizationPath,
  buildEnvDeltaPlan,
  CADDYFILE_PATH,
  CATALOG_PATH,
  type EnvPlanCurrent,
  EnvPlanError,
  type EnvPlanOp,
  overlayPath,
  SCHEDULER_CONFIGMAP_PATH,
} from "./env-membership-plan";

const SLUG = "blue";

const KUST_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../<env>-appsets-application.yaml). One AppSet
# per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

const kustWith = (env: string, nodes: readonly string[]): string =>
  `${KUST_HEADER}\n${nodes
    .map((n) => `  - ${env}-${n}-applicationset.yaml`)
    .join("\n")}\n`;

// node-template overlay carrying the node-at-root migrate command renderOverlay requires.
const TEMPLATE_OVERLAY = `namespace: cogni-candidate-a-node-template
resources:
  - ../../../base/node-app
patches:
  - target: { kind: Service }
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30200
images:
  - name: node-app
    newName: ghcr.io/cogni-dao/cogni-template-node-template
initContainers:
  migrate: exec node /app/app/migrate.mjs /app/app/migrations
`;

const APPSET_TEMPLATE = `metadata:
  name: cogni-__ENV__-__NODE__
spec:
  generators:
    - git:
        files:
          - path: "infra/catalog/__NODE__.yaml"
`;

const CADDYFILE = `# ── operator (primary domain) → k3s NodePort 30000 ──
{$DOMAIN} {
  reverse_proxy host.docker.internal:30000
}

# ── blue node → k3s NodePort 31100 ──────────────────────────────────
{$BLUE_DOMAIN:blue.localhost} {
  encode zstd gzip

  @public path /api/v1/public/*
  handle @public {
    reverse_proxy {$BLUE_UPSTREAM:host.docker.internal:31100} {
      header_up X-Real-IP {remote_host}
      transport http {
        response_header_timeout 10s
      }
    }
  }

  reverse_proxy {$BLUE_UPSTREAM:host.docker.internal:31100}

  log {
    format json
    output file /data/logs/caddy/access-blue.log {
      roll_size 10MB
      roll_keep 7
      roll_keep_for 168h
    }
  }
}
`;

const SCHEDULER_CONFIGMAP = `apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-worker
data:
  COGNI_NODE_ENDPOINTS: "blue=http://blue-node-app:3000,11111111-1111-1111-1111-111111111111=http://blue-node-app:3000,operator=http://operator-node-app:3000,22222222-2222-2222-2222-222222222222=http://operator-node-app:3000"
`;

const catalogWith = (envs: readonly string[]): string =>
  `name: ${SLUG}
type: node
port: 3200
node_port: 31100
dockerfile: nodes/${SLUG}/app/Dockerfile
image_tag_suffix: "-${SLUG}"
migrator_tag_suffix: "-${SLUG}-migrate"
candidate_a_branch: deploy/candidate-a-${SLUG}
preview_branch: deploy/preview-${SLUG}
production_branch: deploy/production-${SLUG}
envs: [${envs.join(", ")}]
path_prefix: nodes/${SLUG}/
`;

function baseCurrent(envs: readonly string[]): EnvPlanCurrent {
  const appsetsKustomizationByEnv: Record<string, string> = {};
  const templateOverlayByEnv: Record<string, string> = {};
  for (const e of envs) {
    appsetsKustomizationByEnv[e] = kustWith(e, ["blue", "operator"]);
    templateOverlayByEnv[e] = TEMPLATE_OVERLAY;
  }
  // preview is the env we ADD in tests, so make its template overlay + kustomization available.
  appsetsKustomizationByEnv.preview ??= kustWith("preview", ["operator"]);
  templateOverlayByEnv.preview ??= TEMPLATE_OVERLAY;
  return {
    catalog: catalogWith(envs),
    templateOverlayByEnv,
    appsetTemplate: APPSET_TEMPLATE,
    appsetsKustomizationByEnv,
    port: 3200,
    nodePort: 31100,
    caddyfile: CADDYFILE,
    schedulerConfigmap: SCHEDULER_CONFIGMAP,
  };
}

const paths = (ops: readonly EnvPlanOp[]): string[] => ops.map((o) => o.path);
const deletes = (ops: readonly EnvPlanOp[]): string[] =>
  ops.filter((o) => o.op === "delete").map((o) => o.path);

describe("buildEnvDeltaPlan — ADD env", () => {
  it("inserts catalog edit + overlay + appset + kustomization fold for the added env", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a"]),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // No deletes on an add.
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH(SLUG),
        overlayPath("preview", SLUG),
        appsetPath("preview", SLUG),
        appsetsKustomizationPath("preview"),
      ].sort()
    );

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    // Overlay rename applied (node-template → blue).
    const overlayOp = res.ops.find(
      (o) => o.path === overlayPath("preview", SLUG)
    );
    if (overlayOp?.op === "upsert") {
      expect(overlayOp.content).toContain("cogni-candidate-a-blue");
    }
    // appsets kustomization now lists blue under preview.
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("preview")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).toContain("preview-blue-applicationset.yaml");
    }
  });

  it("is idempotent when the env is already present", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — REMOVE env (partial, non-candidate-a)", () => {
  it("drops the env line + sha:null deletes overlay+appset + regenerates kustomization", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // Overlay + appset are DELETED (sha:null in the adapter).
    expect(deletes(res.ops).sort()).toEqual(
      [overlayPath("production", SLUG), appsetPath("production", SLUG)].sort()
    );
    // Catalog edited + kustomization regenerated without blue.
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("production")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "production-blue-applicationset.yaml"
      );
    }
    // The catalog row itself is NOT deleted on a partial remove.
    expect(deletes(res.ops)).not.toContain(CATALOG_PATH(SLUG));
  });

  it("is idempotent when the env is already absent", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — FULL DECOMMISSION", () => {
  it("requires explicit decommission intent — a bare candidate-a remove is refused (422)", () => {
    try {
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false, // no decommission:true → must NOT silently destroy the node
        current: baseCurrent(["candidate-a", "preview", "production"]),
      });
      throw new Error("expected EnvPlanError");
    } catch (err) {
      expect(err).toBeInstanceOf(EnvPlanError);
      const e = err as EnvPlanError;
      expect(e.code).toBe("decommission_requires_intent");
      expect(e.status).toBe(422);
    }
  });

  it("removing candidate-a (decommission:true) deletes catalog + all overlays/appsets + caddy + scheduler", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      decommission: true,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("decommission");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");
    expect(res.nextEnvs).toEqual([]);

    // Catalog row + every env's overlay + appset are deleted.
    const del = deletes(res.ops);
    expect(del).toContain(CATALOG_PATH(SLUG));
    for (const env of ["candidate-a", "preview", "production"]) {
      expect(del).toContain(overlayPath(env, SLUG));
      expect(del).toContain(appsetPath(env, SLUG));
    }
    // Caddy + scheduler regenerated WITHOUT blue (env-independent, only on full removal).
    const caddyOp = res.ops.find((o) => o.path === CADDYFILE_PATH);
    if (caddyOp?.op === "upsert") {
      expect(caddyOp.content).not.toContain("blue node");
    }
    const schedOp = res.ops.find((o) => o.path === SCHEDULER_CONFIGMAP_PATH);
    if (schedOp?.op === "upsert") {
      expect(schedOp.content).not.toContain("blue=http://blue-node-app");
      expect(schedOp.content).toContain("operator=http://operator-node-app");
    }
  });

  it("removing the LAST remaining env (decommission:true) is also a full decommission", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      decommission: true,
      current: baseCurrent(["candidate-a"]),
    });
    expect(res.kind).toBe("decommission");
  });
});

describe("CANDIDATE_A_ALWAYS", () => {
  // Per the verb's contract, removing candidate-a is NEVER a partial trim — it is the full-decommission
  // path (the node leaves the catalog, taking preview/production with it). It therefore requires explicit
  // `decommission:true` intent (the bare-remove refusal is covered above); WITH intent it decommissions to
  // an empty set. This pins that the node can never end up with envs-but-no-candidate-a.
  it("removing candidate-a (with intent) decommissions to an empty set (never a candidate-a-less node)", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      decommission: true,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("decommission");
    if (res.kind === "decommission") {
      // The surviving env-set is empty — there is no candidate-a-less node.
      expect(res.nextEnvs).toEqual([]);
    }
  });

  // The defensive 422 guard fires only on a corrupt input: a current row that already lacks candidate-a,
  // where a partial non-candidate-a remove would leave a candidate-a-less (still non-empty) set.
  it("refuses (422 candidate_a_always) a partial remove that would leave a candidate-a-less set", () => {
    const corrupt: EnvPlanCurrent = baseCurrent(["preview", "production"]);
    try {
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "production",
        present: false,
        current: corrupt,
      });
      throw new Error("expected EnvPlanError");
    } catch (err) {
      expect(err).toBeInstanceOf(EnvPlanError);
      const e = err as EnvPlanError;
      expect(e.code).toBe("candidate_a_always");
      expect(e.status).toBe(422);
    }
  });
});
