// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/repo-spec`
 * Purpose: Render a new node's `.cogni/repo-spec.yaml` — the web3-anchored identity + governance
 *   doc — so the operator can author a node-birth PR carrying the node's own identity instead of
 *   cloning the template's.
 * Scope: Pure transformer over server-verified DAO addresses + identity. `scope_id` is derived from
 *   `node_id` (uuidv5), never passed; `scope_key` defaults to `default`; payments stay
 *   `pending_activation` (formation is governance-only).
 * Invariants: REPO_SPEC_IS_IDENTITY_SSOT — `node_id` is the single identity authority. SCOPE_ID_IS_DERIVED
 *   — `scope_id = uuidv5("default", node_id)`, matching `features/nodes/repo-spec-builder`. FORMATION_IS_GOVERNANCE_ONLY.
 *   BORN_REVIEWABLE — the mint overwrites the template's `.cogni/repo-spec.yaml` wholesale, so the
 *   default review `gates:` MUST be emitted here or every minted node is born with zero gates
 *   ("no gates, pass" — the `cogni-test-org/ay` gap). The rule files the gates reference ship in the
 *   node-template repo (`.cogni/rules/`, inherited by the template fork) and stay in
 *   lockstep with `nodes/node-template/.cogni/rules/`. Gate set coordinated with Lane A (review path).
 * Side-effects: none — pure function, no IO, no env.
 * Links: nodes/node-template/.cogni/repo-spec.yaml, nodes/node-template/.cogni/rules/, src/features/nodes/repo-spec-builder.ts, docs/spec/node-ci-cd-contract.md, task.5092
 * @public
 */

import { v5 as uuidv5 } from "uuid";

import type { NodeKnowledgeRemote } from "../knowledge-remote";

export interface RenderRepoSpecInput {
  readonly nodeId: string;
  readonly chainId: number;
  readonly daoContract?: string | undefined;
  readonly pluginContract?: string | undefined;
  readonly signalContract?: string | undefined;
  readonly knowledgeRemote?: NodeKnowledgeRemote | undefined;
}

/** uuidv5 of the scope key under the node_id namespace — matches `repo-spec-builder`'s derivation. */
function deriveScopeId(nodeId: string): string {
  return uuidv5("default", nodeId);
}

/** Render `.cogni/repo-spec.yaml` for a freshly-formed node (pending payment activation). */
export function renderRepoSpec(input: RenderRepoSpecInput): string {
  const scopeId = deriveScopeId(input.nodeId);
  const daoLines = [
    input.daoContract ? `  dao_contract: "${input.daoContract}"` : undefined,
    input.pluginContract
      ? `  plugin_contract: "${input.pluginContract}"`
      : undefined,
    input.signalContract
      ? `  signal_contract: "${input.signalContract}"`
      : undefined,
    `  chain_id: "${input.chainId}"`,
  ]
    .filter((l): l is string => l !== undefined)
    .join("\n");

  return `# Generated by Node Formation — node identity + governance.
# node_id is the single identity authority (REPO_SPEC_IS_IDENTITY_SSOT);
# scope_id is derived as uuidv5("default", node_id) and must never change.
# See docs/spec/identity-model.md, docs/spec/node-formation.md.

schema_version: "0.1.4"

node_id: "${input.nodeId}"
scope_id: "${scopeId}"
scope_key: "default"

cogni_dao:
${daoLines}

${input.knowledgeRemote ? renderKnowledgeBlock(input.knowledgeRemote) : ""}

# Payment rails — activate with: pnpm node:activate-payments
payments:
  status: pending_activation

# Born-reviewable default gates (BORN_REVIEWABLE). No \`nodes:\` registry → the operator's
# review path resolves this minted repo as a single-node fork and runs these gates against
# the repo-root \`.cogni/rules/\` shipped by the node-template. Tune per node post-mint.
gates:
  - type: review-limits
    id: review_limits
    with:
      max_changed_files: 50
      max_total_diff_kb: 1500
  - type: ai-rule
    with:
      rule_file: pr-syntropy-coherence.yaml
  - type: ai-rule
    with:
      rule_file: patterns-and-docs.yaml
  - type: ai-rule
    with:
      rule_file: repo-goal-alignment.yaml
`;
}

function renderKnowledgeBlock(remote: NodeKnowledgeRemote): string {
  return `knowledge:
  database: "${remote.database}"
  remote:
    provider: dolthub
    owner: "${remote.owner}"
    repo: "${remote.repo}"
    url: "${remote.url}"
    custody: cogni-owned`;
}
