apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: f66b260b-4633-41e2-8711-b7c1b8449cc1
  namespace: cogni-preview
  labels:
    cogni.io/node-id: f66b260b-4633-41e2-8711-b7c1b8449cc1
    cogni.io/environment: preview
    cogni.io/node: toks5
spec:
  nodeId: f66b260b-4633-41e2-8711-b7c1b8449cc1
  environment: preview
  bundle:
    ref: ghcr.io/cogni-dao/toks5@sha256:4a014d29d4e6eae6e98c12a23939dd8cfaaaf069e1e75f4937aaab1028bd1804
    source:
      repository: cogni-dao/toks5
      sha: 1215bfb1627448582d8ff4dee358d660658a173a
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks5@sha256:a228bf533d9c2125e2e701eb7f7c588d2db392b69bde5da39b787a25782fe281
  workload:
    name: toks5
    publicHost: toks5-preview.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Close
  leaseGeneration: 0
  actuatorNamespace: cogni-production
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
