# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Cogni-DAO
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - provider.yaml
  - functions.yaml
  - providerconfig.yaml
  - externalsecret.yaml
