apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-preview
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: preview
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: preview
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:ea6482e6a19ae360290937e8558c4fa48c8b329bcff4fd7409611f87bae4b8ad
    source:
      repository: cogni-dao/toks4
      sha: 783b41d5b9b740d35c9d5376384c9809db1bb879
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:fd295363fe780e142e2961e556d3d82d9b417ca03bcaf6c0a085a3866e31e105
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:811d7ac29d2cf3a7b21d5af44d14e8a3d87730a4405269ef4589b5aaf495a9a6
  workload:
    name: toks4
    publicHost: toks4-preview.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: DOLTGRES_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Close
    onGiveUp: Hold
  leaseGeneration: 1
  actuatorNamespace: cogni-production
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
