apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: levelup-compute-env-secrets-reader
  namespace: cogni-preview
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - levelup-compute-env-secrets
    verbs:
      - get
