apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  namespace: cogni-preview
  labels:
    cogni.io/node-id: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
    cogni.io/environment: preview
    cogni.io/node: node-template
spec:
  nodeId: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  environment: preview
  bundle:
    ref: ghcr.io/cogni-dao/node-template@sha256:2dea27cf5d1cbec704b4caed0f0f4cba3333ae884eea47bfdad41c84ccd8d464
    source:
      repository: cogni-dao/node-template
      sha: 48c603c6ab91d022896aaa884fafb3dd5a295d72
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/node-template@sha256:6064776ebe1a375f37761871a0cce9086c24d3e129f49d444425555fc050edd2
  workload:
    name: node-template
    publicHost: node-template-preview.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
