apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  namespace: cogni-preview
  labels:
    cogni.io/node-id: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
    cogni.io/environment: preview
    cogni.io/node: node-template
spec:
  nodeId: b927a9dd-6132-4fc9-a51e-e3cee2568e3c
  environment: preview
  bundle:
    ref: ghcr.io/cogni-dao/node-template@sha256:e461a8ce7a67e88a8af1e7fdb3286abf147da34ac2eb39f9a561034b7e4ac441
    source:
      repository: cogni-dao/node-template
      sha: f39ed6f159e43c7a50779b406c81ecd24fd4bae5
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/node-template@sha256:2b038a7e0dfb2997729836d1789f53f990fc73500b192256c7cf534faad9756e
  workload:
    name: node-template
    publicHost: node-template-preview.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
