// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@features/nodes/repo-spec-builder`
 * Purpose: Build the governance-only `.cogni/repo-spec.yaml` emitted by node formation.
 * Scope: Pure transformer — takes server-verified DAO addresses and emits the YAML that
 *   setup.verify returns and the publish step commits. No IO, no env.
 * Invariants: FORMATION_IS_GOVERNANCE_ONLY — payments remain pending_activation.
 * Side-effects: none
 * Links: docs/spec/node-formation.md, packages/repo-spec, task.5083
 * @public
 */

import { v5 as uuidv5 } from "uuid";

export interface NodeRepoSpecInput {
  nodeId: string;
  chainId: number;
  daoAddress: string;
  pluginAddress: string;
  signalAddress: string;
}

export function buildPendingActivationRepoSpecYaml(
  input: NodeRepoSpecInput
): string {
  const scopeId = uuidv5("default", input.nodeId);

  return `# Generated by Node Formation
# Copy this to .cogni/repo-spec.yaml

schema_version: "0.1.4"

# Unique identity for this node deployment.
# Generated once at init; must never change for an existing deployment.
node_id: "${input.nodeId}"

# Governance domain. Derived from node_id + the default scope key.
scope_id: "${scopeId}"
scope_key: "default"

cogni_dao:
  dao_contract: "${input.daoAddress}"
  plugin_contract: "${input.pluginAddress}"
  signal_contract: "${input.signalAddress}"
  chain_id: "${input.chainId}"

# Payment rails — activate with: pnpm node:activate-payments
payments:
  status: pending_activation
`;
}
