// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@features/nodes/repo-spec-builder`
 * Purpose: Build the complete `.cogni/repo-spec.yaml` for a registered node from its DB row.
 * Scope: Pure transformer — takes the `nodes` row at status >= payments_ready and emits the YAML
 *   that the publish step will commit to the target repo. No IO, no env.
 * Invariants: REPO_SPEC_COMPLETE — DAO + operator_wallet + payments_in.credits_topup are all populated.
 * Side-effects: none
 * Links: docs/spec/node-formation.md, packages/repo-spec, task.5083
 * @public
 */

import { v5 as uuidv5 } from "uuid";

import { CHAINS } from "@/shared/web3";

export interface NodeRepoSpecInput {
  nodeId: string;
  chainId: number;
  daoAddress: string;
  pluginAddress: string;
  signalAddress: string;
  operatorWalletAddress: string;
  splitAddress: string;
}

const CHAIN_KEY_BY_ID: Record<number, "Base" | "Sepolia"> = {
  [CHAINS.BASE.chainId]: "Base",
  [CHAINS.SEPOLIA.chainId]: "Sepolia",
};

export function buildCompleteRepoSpecYaml(input: NodeRepoSpecInput): string {
  const scopeId = uuidv5("default", input.nodeId);
  const chainKey = CHAIN_KEY_BY_ID[input.chainId];
  if (!chainKey) {
    throw new Error(
      `Unsupported chainId for repo-spec emission: ${input.chainId}`
    );
  }

  return `# Generated by the Cogni operator setup wizard.
# Do not edit by hand — re-run the wizard to refresh.

schema_version: "0.1.4"

node_id: "${input.nodeId}"

scope_id: "${scopeId}"
scope_key: "default"

cogni_dao:
  dao_contract: "${input.daoAddress}"
  plugin_contract: "${input.pluginAddress}"
  signal_contract: "${input.signalAddress}"
  chain_id: "${input.chainId}"

operator_wallet:
  address: "${input.operatorWalletAddress}"

payments_in:
  credits_topup:
    provider: cogni-usdc-backend-v1
    receiving_address: "${input.splitAddress}"
    allowed_chains:
      - ${chainKey}
    allowed_tokens:
      - USDC

payments:
  status: active
`;
}
