apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  namespace: cogni-preview
  labels:
    cogni.io/node-id: f97f68f2-8406-4a3b-b5a9-d579b779f19d
    cogni.io/environment: preview
    cogni.io/node: beacon
spec:
  nodeId: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  environment: preview
  bundle:
    ref: ghcr.io/cogni-dao/beacon@sha256:c0c0a2552ba027317d763f3ebb5041730de83b4ccd58ca4ef59c5d3512053860
    source:
      repository: cogni-dao/beacon
      sha: 88d7d87b8bb6a3fdb7c604676990cd2ba8fcf777
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/beacon@sha256:3ff57f0dc444783c326abc0d39525531f5e7d963e9dc0f706c88dddb37bb36e7
  workload:
    name: beacon
    publicHost: beacon-preview.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
