apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  namespace: cogni-preview
  labels:
    cogni.io/node-id: f97f68f2-8406-4a3b-b5a9-d579b779f19d
    cogni.io/environment: preview
    cogni.io/node: beacon
spec:
  nodeId: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  environment: preview
  bundle:
    ref: ghcr.io/cogni-dao/beacon@sha256:68182a57826bf1e417e575a0733a4dc6b8f695e802efdb546c139b0148841261
    source:
      repository: cogni-dao/beacon
      sha: 547270e1f03e91b333ba6128d2a56ffadeb4e1c7
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/beacon@sha256:6011cedbc9c208d6c8d79483f44dc8ef669ead63e7cd781e610d237518097078
  workload:
    name: beacon
    publicHost: beacon-preview.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
