apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  namespace: cogni-preview
  labels:
    cogni.io/node-id: f97f68f2-8406-4a3b-b5a9-d579b779f19d
    cogni.io/environment: preview
    cogni.io/node: beacon
spec:
  nodeId: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  environment: preview
  bundle:
    ref: ghcr.io/cogni-dao/beacon@sha256:938866626914473409d5986fb74b75c4bcc41640f226172f0e80ff56551c5f2e
    source:
      repository: cogni-dao/beacon
      sha: f4d4e4d4b6220abb89003b7073a6645a1cd270b0
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/beacon@sha256:25ec03044e944f789c21eff7a40abd67f6837f5c9802a8dbe65d655e7921cc36
  workload:
    name: beacon
    publicHost: beacon-preview.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
