name: hello-world
type: node
port: 3200
node_port: 30500
dockerfile: nodes/hello-world/app/Dockerfile
image_tag_suffix: "-hello-world"
migrator_tag_suffix: "-hello-world-migrate"
candidate_a_branch: deploy/candidate-a-hello-world
preview_branch: deploy/preview-hello-world
production_branch: deploy/production-hello-world
path_prefix: nodes/hello-world/
