// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/secrets/node-secrets-allowlist.data`
 * Purpose: Gate-2 allowlist for node self-serve secret writes — the set of A2
 *   keys each node slug is permitted to set/rotate at `cogni/<env>/<slug>/<KEY>`.
 * Scope: Static data only — no IO, no env, no `fs`. This is the build-time
 *   typed-module form of `infra/secrets-catalog.yaml`'s A2 entries, because the
 *   operator runtime image carries neither that catalog nor the loader (verified
 *   vs `nodes/operator/app/Dockerfile`; same constraint as the #1479 homepage
 *   showcase). The route MUST read this module, never `fs`-read the catalog.
 * Invariants:
 *   - A2_ONLY: every key here is tier A2 in the catalog (`service: <slug>`).
 *   - DEPTH_NOT_FLOOR: this gate bounds key-shape; cross-tenant is already closed
 *     by gate 1 (OpenFGA per-node) + gate 3 (OpenBao `_system`/`_shared` deny). A
 *     stale/missing entry is self-inflicted on the node's own path, never cross-node.
 *   - FAIL_CLOSED: an unknown slug or undeclared key is refused, never defaulted.
 * Codegen: hand-curated for v0; the drift gate that regenerates this from the
 *   catalog A2 entries is the tracked follow-up (see design §Security boundary gate 2).
 * Side-effects: none
 * Links: docs/design/node-self-serve-secrets.md, infra/secrets-catalog.yaml (A2),
 *   src/app/api/v1/nodes/[id]/secrets/route.ts
 * @public
 */

/**
 * Node slug → the A2 keys that slug may self-serve. Empty by design today: the
 * legacy node dirs were purged (#1631 canary/resy/ayo/…; #1330 stripped poly),
 * and no surviving node (`operator`, `scheduler-worker`) declares a node-owner
 * A2 self-serve secret. So every write fail-closes at gate 2 — correct, not a gap.
 *
 * This map MUST be regenerated by build-time codegen from the catalog's A2
 * `service: <slug>` entries (`infra/secrets-catalog.yaml` + `nodes/<slug>/.cogni/
 * secrets-catalog.yaml`), per Invariant 14 `CATALOG_IS_THE_ONE_READER` — a
 * hand-authored parallel list is exactly what that invariant forbids. The
 * operator runtime image carries no catalog/loader, so the codegen runs at build.
 * Until then the feature's real customer is a wizard-minted node whose own
 * catalog declares an A2 key (see docs/design/node-self-serve-secrets.md §E2E).
 */
export const NODE_SECRETS_ALLOWLIST: Readonly<
  Record<string, readonly string[]>
> = {} as const;

/**
 * Gate 2: is `key` an allowlisted A2 secret for `nodeSlug`? Fail-closed — an
 * unknown slug or undeclared key returns false. The caller resolves the path as
 * `cogni/<env>/<nodeSlug>/<key>` only after this passes.
 */
export function isNodeSecretAllowed(nodeSlug: string, key: string): boolean {
  return NODE_SECRETS_ALLOWLIST[nodeSlug]?.includes(key) ?? false;
}
