apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: 4b06359a-a859-4399-888e-a8c7a6696f7e
  namespace: cogni-production
  labels:
    cogni.io/node-id: 4b06359a-a859-4399-888e-a8c7a6696f7e
    cogni.io/environment: production
    cogni.io/node: poly
spec:
  nodeId: 4b06359a-a859-4399-888e-a8c7a6696f7e
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/poly@sha256:22402e414a60d6f1ac3b6f58909992bf8c8360c525909c5caca0c3c6d93e6e75
    source:
      repository: cogni-dao/poly
      sha: 400494a523baf671672c06bfcc957a980f63b37d
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/poly@sha256:b9b8273e1005806b31067bdf6547cef4f5d7a2601c147baaed5fe45f4f813f24
  workload:
    name: poly
    publicHost: poly.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
