apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: 921b1d1d-4ded-4a6d-b3f1-f7d6affa406a
  namespace: cogni-production
  labels:
    cogni.io/node-id: 921b1d1d-4ded-4a6d-b3f1-f7d6affa406a
    cogni.io/environment: production
    cogni.io/node: red
spec:
  nodeId: 921b1d1d-4ded-4a6d-b3f1-f7d6affa406a
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/red@sha256:faf8dbd6f426a4ecae1e17b7550cf8dfe4d79d6f9f4ea0380105e5a1c937f7b7
    source:
      repository: cogni-dao/red
      sha: 3e1e016ff829c41422dc690a932ed426952de93f
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/red@sha256:999ab37c968b322138374ae04f348ff822bcf6b35fddd6a3e040cf19140f78a4
  workload:
    name: red
    publicHost: red.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: DOLTGRES_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Hold
    onGiveUp: Hold
  leaseGeneration: 0
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
