apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cogni-candidate-b

resources:
  - ../../../base/sandbox-openclaw

images:
  - name: ghcr.io/cogni-dao/cogni-sandbox-openclaw
    newTag: "latest"
