apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-template-compute-env-secrets-reader
  namespace: cogni-production
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - node-template-compute-env-secrets
    verbs:
      - get
