apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: 557d8b59-8e3b-42f0-9aeb-a5c171296556
  namespace: cogni-production
  labels:
    cogni.io/node-id: 557d8b59-8e3b-42f0-9aeb-a5c171296556
    cogni.io/environment: production
    cogni.io/node: levelup
spec:
  nodeId: 557d8b59-8e3b-42f0-9aeb-a5c171296556
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/levelup@sha256:6b81e1dc131fe9d9168417bd5f1d9571daf528a8b03104d31705e19b397b5f49
    source:
      repository: cogni-dao/levelup
      sha: 461dde98dabc06b12532255eecbf68dbb75ab972
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/levelup@sha256:a52f587407a5f6a0951d131bebc280cd0965c5ef9505275ef6da38a386bdae28
  workload:
    name: levelup
    publicHost: levelup.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: DOLTGRES_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Hold
    onGiveUp: Hold
  leaseGeneration: 2
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
