import {
  DEFAULT_LANGGRAPH_GRAPH_ID,
  LANGGRAPH_CATALOG as BASE_LANGGRAPH_CATALOG,
  LANGGRAPH_GRAPH_IDS as BASE_LANGGRAPH_GRAPH_IDS,
} from "@cogni/langgraph-graphs";

export const LANGGRAPH_CATALOG = BASE_LANGGRAPH_CATALOG;
export {
  DEFAULT_LANGGRAPH_GRAPH_ID,
  BASE_LANGGRAPH_GRAPH_IDS as LANGGRAPH_GRAPH_IDS,
};
export * from "@cogni/langgraph-graphs/graphs";
