apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  namespace: cogni-production
  labels:
    cogni.io/node-id: f97f68f2-8406-4a3b-b5a9-d579b779f19d
    cogni.io/environment: production
    cogni.io/node: beacon
spec:
  nodeId: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/beacon@sha256:2e9c55dd4b4bc3f6cbbe002ec8ac6b1e5eaf26e46a61ebeabe821b4d90a9cf1d
    source:
      repository: cogni-dao/beacon
      sha: 45f6895d3693cecec9804ccec97153c693966ec9
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/beacon@sha256:53d57291844b70bdba64d4bfe55e78b59d2778e74768d241013f99c316e6c7fe
  workload:
    name: beacon
    publicHost: beacon.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
