apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  namespace: cogni-production
  labels:
    cogni.io/node-id: f97f68f2-8406-4a3b-b5a9-d579b779f19d
    cogni.io/environment: production
    cogni.io/node: beacon
spec:
  nodeId: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/beacon@sha256:2492080c7d4ca183c6a534f1deb5cd9ece489f1950e26e8f9b3ffcd51429ee2a
    source:
      repository: cogni-dao/beacon
      sha: 88d7d87b8bb6a3fdb7c604676990cd2ba8fcf777
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/beacon@sha256:ad4c0384f41285d1ec5b980f8a5baafeebcc331fd8d8c561a9ced954ab6c7674
  workload:
    name: beacon
    publicHost: beacon.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
