apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  namespace: cogni-production
  labels:
    cogni.io/node-id: f97f68f2-8406-4a3b-b5a9-d579b779f19d
    cogni.io/environment: production
    cogni.io/node: beacon
spec:
  nodeId: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/beacon@sha256:82421677c29cc0fa9b815c7e2c8488c5ff67366320b677a9b99ca30f79e34f1f
    source:
      repository: cogni-dao/beacon
      sha: 5b5fb2eea3930527f92346d2f8c385fe8c4ef432
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/beacon@sha256:634a1bda0055343ab640603100056d812ba08d28b4236564406eaf44f5b80d08
  workload:
    name: beacon
    publicHost: beacon.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Hold
  leaseGeneration: 0
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
