apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  namespace: cogni-production
  labels:
    cogni.io/node-id: f97f68f2-8406-4a3b-b5a9-d579b779f19d
    cogni.io/environment: production
    cogni.io/node: beacon
spec:
  nodeId: f97f68f2-8406-4a3b-b5a9-d579b779f19d
  environment: production
  bundle:
    ref: ghcr.io/cogni-dao/beacon@sha256:52dae7d97847b93b65a37cf7612156fb18a4d08fbe35ce52288727fec89de087
    source:
      repository: cogni-dao/beacon
      sha: f9d25b63f4c9bfea1362a6057b5bc48e273a47af
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/beacon@sha256:519a9e5758e5e61491db3415040758d29189419b6cce4bf533c487949a726148
  workload:
    name: beacon
    publicHost: beacon.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Hold
  leaseGeneration: 0
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
