apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-candidate-a
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: candidate-a
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: candidate-a
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:6b59e164732ecaae66d3b886304897d6dfb43379a5e2c78cdf71f97e15b5bfdf
    source:
      repository: cogni-dao/toks4
      sha: b87fc1183098e88e233ff313fbaf2a69a474ffd8
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:ecf442c9edb5ac36d1bcb8f44cc9c6646e1008e6451d44c306073d35a14e356c
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:eb1745e1bb02a41b41c7ec56e0fd6bddb7c82b2be8ee6d03031e826e496a2903
  workload:
    name: toks4
    publicHost: toks4-test.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
          - key: LITELLM_VIRTUAL_KEY
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
