apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-candidate-a
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: candidate-a
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: candidate-a
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:8a207c4c041387fe369e1c5fe006e0f07664bee17fffdb5d89abc1b1a82fbbd7
    source:
      repository: cogni-dao/toks4
      sha: beafd0c66b6bb0148d40deb60a433683324a3914
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:dae59cc3e0e61af3ddfea21a2511b6223a45cb65979e967eee831f9f58939624
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:fc960392a7e46945d3bd9793fd4220e4ac5429cef06f2baba68771d66b191a73
  workload:
    name: toks4
    publicHost: toks4-test.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: DOLTGRES_URL
          - key: EVM_RPC_URL
          - key: LITELLM_VIRTUAL_KEY
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
  migration:
    policy: RequireBeforeServing
  bootPolicy:
    onDeadline: Close
    onGiveUp: Replace
  leaseGeneration: 4
  placement:
    requiredCountries:
      - BG
      - CH
      - FI
      - NL
      - PT
  actuatorNamespace: cogni-production
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni.vm.cognidao.org
