apiVersion: compute.cogni.io/v1alpha1
kind: XComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-candidate-a
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: candidate-a
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: candidate-a
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:ae956f8dded458bf03fe406111fac5d7669279cd619027765a05ad3cd56e4890
    source:
      repository: cogni-dao/toks4
      sha: 07e8fa3d384131320aeeaa5d690cf29faf93c1ab
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:7e940be0d76cc991d4095e6d1eaf78f16dd345da2304a02fb543ba7465040de7
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:4f31c984676e0f037dfbfecaf1cc55dbe71a4f387999f6790005a7999cca0619
  workload:
    name: toks4
    publicHost: toks4-test.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
          - key: LITELLM_VIRTUAL_KEY
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
  migration:
    policy: RequireBeforeTransaction
  bootPolicy:
    onDeadline: Close
  leaseEpoch: 0
  dns:
    provider: cloudflare
    zoneId: 23220356c352c5831c6af57887b11a27
  runtime:
    substrateHost: cogni-candidate-a.vm.cognidao.org
